services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: workshop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh

#  app:
#    build: .
#    container_name: os_management
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/workshop
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: password
#      JWT_SECRET: akmsdkmasfnjsgknakmsdkmasdkmsadfkmdsakmdkmsadsa
#      JWT_EXPIRATION: 86400000
#
#  validation:
#    image: curlimages/curl:8.10.1
#    container_name: os_management_validation
#    depends_on:
#      - postgres
#      - app
#    environment:
#      APP_URL: http://app:8080
#    volumes:
#      - ./validation.sh:/validation.sh
#    command: ["sh", "-c", "sleep 20 && sh /validation.sh"]
