apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-management
  namespace: os-management
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: developer
    spec:
      containers:
        - name: os-management
          env:
            - name: DD_ENV
              value: developer
