apiVersion: v1
kind: ConfigMap
metadata:
  name: os-management-config
  namespace: os-management
data:
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: workshop
  # Requires DD_API_KEY in os-management-secret.
  DD_METRICS_ENABLED: "true"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:15432/workshop
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "false"
  JWT_EXPIRATION: "86400000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: os-management
data:
  POSTGRES_DB: workshop
  POSTGRES_USER: user
  PGDATA: /var/lib/postgresql/data/pgdata
