apiVersion: v1
kind: ConfigMap
metadata:
  name: os-management-config
  namespace: os-management
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.os-management.svc.cluster.local:5432/workshop"
  JAVA_OPTS: "-Xms256m -Xmx512m"
  LOG_LEVEL: "INFO"
