apiVersion: v1
kind: ConfigMap
metadata:
  name: os-management-config
  namespace: os-management
data:
  DB_HOST: "mysql.os-management.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "os_management"
  JAVA_OPTS: "-Xms256m -Xmx512m"
  LOG_LEVEL: "INFO"
