apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: os-management
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - postgres-init-job.yaml
  - base
  - ingress.yaml
  - hpa.yaml

patches:
  - path: datadog-production.yaml

configMapGenerator:
  - name: postgres-init
    files:
      - init.sh

generatorOptions:
  disableNameSuffixHash: true
