apiVersion: v1
kind: Secret
metadata:
  name: os-management-db-secret
  namespace: os-management
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "your_db_user_here"
  SPRING_DATASOURCE_PASSWORD: "your_secure_password_here"
  JWT_SECRET: "your_jwt_secret_at_least_32_chars_here"
  JWT_EXPIRATION: "86400000"
